//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Storefront.DATA.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class VideoGame
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VideoGame()
        {
            this.Creators = new HashSet<Creator>();
        }
    
        public int VidGameID { get; set; }
        public string Upc { get; set; }
        public string VideoGameTitle { get; set; }
        public string Description { get; set; }
        public int ESRBRatingID { get; set; }
        public int GenreID { get; set; }
        public int PublisherID { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<System.DateTime> PublishDate { get; set; }
        public Nullable<int> CreatorID { get; set; }
        public byte[] Image { get; set; }
        public Nullable<int> InStock { get; set; }
        public Nullable<int> UnitsSold { get; set; }
        public Nullable<bool> OnBackOrder { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Creator> Creators { get; set; }
        public virtual ESRBRating ESRBRating { get; set; }
        public virtual Genre Genre { get; set; }
        public virtual Publisher Publisher { get; set; }
    }
}
